### ISSUE TITLE
question on ewma function not using existing value

### ISSUE THREAD

**Issue by client9** [VividCortex/gohistogram#18]
hello,
I find the following a bit odd.  I'll go take a look at the Java code, but either its wrong or can be simplified.

``` go
func ewma(existingVal float64, newVal float64, alpha float64) (result float64) {
	result = newVal*(1-alpha) + existingVal*alpha  // *** existingVal is always 0 ??
	return
}

func (h *WeightedHistogram) scaleDown(except int) {
	for i := range h.bins {
		if i != except {
			h.bins[i].count = ewma(h.bins[i].count, 0, h.alpha) //****  <--- 0 ??
		}
	}
}
```

**Comment by Preetam** [comment]
Hi,

`scaleDown` decays every bin except for the index `except`. For the `Add` method, the idea was to increment the appropriate bucket by 1 and scale down everything else.

I wasn't as good at programming (or Go) 2 years ago, so there is a lot to fix in this package. But the two functions you've copied are correct.

**Comment by client9** [comment]
thanks for your time reviewing this,  regards, --nickg
