### ISSUE TITLE
Got panic under unknown circumstances

### ISSUE THREAD

**Issue by gaplyk** [VividCortex/gohistogram#21]
When I'm using numeric histograms in different goroutines getting panic from time to time:
runtime error: index out of range

Panic is here:
github.com/VividCortex/gohistogram/numerichistogram.go:124

**Comment by Preetam** [comment]
> When I'm using numeric histograms in different goroutines 

This package isn't goroutine safe. Please use a mutex :). Let me know if you have any questions.
