### ISSUE TITLE
Set a version and tag a release

### ISSUE THREAD

**Issue by zoofood** [VividCortex/gohistogram#22]
I think this project is very useful and I've noted other projects in Go use it as well. Merely a suggestion, but I think you could make things simpler for people pulling this in if you have a tagged release tag to pull from. (See https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases) It is super quick to add in Github.

Thanks for writing this.

**Comment by Preetam** [comment]
Sorry for the delay. I'll take care of it.

**Comment by Preetam** [comment]
Done. https://github.com/VividCortex/gohistogram/releases/tag/v1.0.0

**Comment by zoofood** [comment]
Awesome, thanks Preetam, and congrats on the version 1.0!
